# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.5
      - image: circleci/postgres:11
        environment:
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: apetitoso_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_TYPE: postgres
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/amaraliou/apetitoso
    steps:
      - checkout
      - run: sudo apt install postgresql-client
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # specify any bash command here prefixed with `run: `
      - run:
          name: Create test database
          command: psql -p 5432 -h localhost -U postgres -c 'create database apetitoso_test'
      - run:
          name: Prepare Postgres extensions
          command: psql -p 5432 -h localhost -U postgres -d apetitoso_test -c 'create extension if not exists "uuid-ossp"' #&& psql -p 5432 -h localhost -U postgres -c 'create extension if not exists "uuid-ossp"'
      - run: 
          name: Install dependencies
          command: go get -v -t -d ./...

      #- run:
          #name: Run models tests
          #environment:
            #DB_USER: postgres
            #DB_PASS: postgres
            #DB_NAME: apetitoso_test
            #DB_HOST: localhost
            #DB_PORT: 5432
            #DB_TYPE: postgres
          #command: make test_models

      #- run:
          #name: Run handlers tests
          #environment:
            #DB_USER: postgres
            #DB_PASS: postgres
            #DB_NAME: apetitoso_test
            #DB_HOST: localhost
            #DB_PORT: 5432
            #DB_TYPE: postgres
          #command: make test_handlers

      - run:
          name: Unit Tests
          environment:
            DB_USER: postgres
            DB_PASS: postgres
            DB_NAME: apetitoso_test
            DB_HOST: localhost
            DB_PORT: 5432
            DB_TYPE: postgres
          command: |
            go get gotest.tools/gotestsum
            mkdir -p ~/test-results
            gotestsum --format standard-verbose --junitfile ~/test-results/handlers-tests.xml ./tests/handlerstest/...
            gotestsum --format standard-verbose --junitfile ~/test-results/models-tests.xml ./tests/modelstest/...
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
          
      - run:
          name: Coverage
          environment:
            DB_USER: postgres
            DB_PASS: postgres
            DB_NAME: apetitoso_test
            DB_HOST: localhost
            DB_PORT: 5432
            DB_TYPE: postgres
          command: go get github.com/wadey/gocovmerge && make coverfile